"""initial schema

Revision ID: 04c8dc5bd11d
Revises: 
Create Date: 2026-05-12 13:09:41.083153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04c8dc5bd11d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lobby', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_column('team2_name')
        batch_op.drop_column('team1_name')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('bot_difficulty',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('bot_difficulty',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('lobby', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team1_name', sa.TEXT(), server_default=sa.text("'Team 1'"), nullable=True))
        batch_op.add_column(sa.Column('team2_name', sa.TEXT(), server_default=sa.text("'Team 2'"), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
